### PR TITLE
Add support for flake8 version 3

### PR DESCRIPTION
**Pull request by stefanor**
Using flake8-polyfill to handle the change to option registration.

### CODE REVIEW

**Comment by Tyrdall** [comment]
Looks good, thanks a lot!

For reference: http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html

**Comment by stefanor** [comment]
Would you mind cutting a release with this patch?

**Comment by Tyrdall** [comment]
Not at all. https://pypi.python.org/pypi/flake8-snippets

**Comment by stefanor** [comment]
Thank you!

**Pull request merged**
